version: '2'

services:
  tracing-server:
     image: openzipkin/zipkin-slim:2
     container_name: tracing-server
     ports:
       - 9411:9411

  config-server:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-config-server:2.3.6
    container_name: config-server
    mem_limit: 1024M
    ports:
      - 8888:8888
    environment:
      - PORT=8888
      - SPRING_PROFILES_ACTIVE=docker
      - TRACING_SERVER_URI=http://tracing-server:9411
      - GIT_CONFIG_URI=https://github.com/benwilcock/spring-petclinic-microservices-config
    depends_on:
      - tracing-server

  discovery-server:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-discovery-server:2.3.6
    container_name: discovery-server
    mem_limit: 1024M
    ports:
      - 8761:8761
    environment:
      - PORT=8761
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - tracing-server
      - config-server

  admin-server:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-admin-server:2.3.6
    container_name: admin-server
    mem_limit: 1024M
    ports:
      - 9090:9090
    environment:
      - PORT=9090
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - config-server
      - discovery-server
      - tracing-server

  customers-service:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-customers-service:2.3.6
    container_name: customers-service
    mem_limit: 1024M
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - config-server
      - discovery-server
      - tracing-server

  visits-service:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-visits-service:2.3.6
    container_name: visits-service
    mem_limit: 1024M
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - config-server
      - discovery-server
      - tracing-server

  vets-service:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-vets-service:2.3.6
    container_name: vets-service
    mem_limit: 1024M
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - config-server
      - discovery-server
      - tracing-server

  gateway-service:
    image: 192.168.1.8:80/spring-petclinic-microservices-fork/spring-petclinic-api-gateway:2.3.6
    container_name: gateway-service
    mem_limit: 1024M
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - config-server
      - discovery-server
      - tracing-server

  # config-checker:
  #   image: spring-petclinic-microservices-fork/spring-petclinic-config-checker:2.3.6
  #   container_name: config-checker
  #   mem_limit: 1024M
  #   ports:
  #     - 9091:9091
  #   environment:
  #     - PORT=9091
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - CONFIG_SERVER_URI=http://config-server:8888
  #     - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
  #   depends_on:
  #     - config-server
  #     - discovery-server
  #     - tracing-server

  # discovery-checker:
  #   image: spring-petclinic-microservices-fork/spring-petclinic-discovery-checker:2.3.6
  #   container_name: discovery-checker
  #   mem_limit: 1024M
  #   ports:
  #     - 9092:9092
  #   environment:
  #     - PORT=9092
  #     - SPRING_PROFILES_ACTIVE=docker
  #     - CONFIG_SERVER_URI=http://config-server:8888
  #     - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
  #   depends_on:
  #     - config-server
  #     - discovery-server
  #     - tracing-server
