version: '2'

services:

  config-server:
    image: benwilcock/spring-petclinic-config-server:2.4.3
    container_name: config-server
    mem_limit: 1024M
    ports:
      - 8888:8888
    environment:
      - PORT=8888
      - SPRING_PROFILES_ACTIVE=docker
      - TRACING_SERVER_URI=http://tracing-server:9411
      - GIT_CONFIG_URI=https://github.com/benwilcock/spring-petclinic-microservices-config

  discovery-server:
    image: benwilcock/spring-petclinic-discovery-server:2.4.3
    container_name: discovery-server
    mem_limit: 1024M
    ports:
      - 8761:8761
    environment:
      - PORT=8761
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - TRACING_SERVER_URI=http://tracing-server:9411
    depends_on:
      - config-server

  admin-server:
    image: benwilcock/spring-petclinic-admin-server:2.4.3
    container_name: admin-server
    mem_limit: 1024M
    ports:
      - 9090:9090
    environment:
      - PORT=9090
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server

  gateway-server:
    image: benwilcock/spring-petclinic-api-gateway:2.4.3
    container_name: gateway-server
    mem_limit: 1024M
    ports:
      - 8080:8080
    environment:
      - PORT=8080
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server

  visits-service:
    image: benwilcock/spring-petclinic-visits-service:2.4.3
    container_name: visits-service
    mem_limit: 1024M
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
      - gateway-server

  vets-service:
    image: benwilcock/spring-petclinic-vets-service:2.4.3
    container_name: vets-service
    mem_limit: 1024M
    ports:
      - 8083:8083
    environment:
      - PORT=8083
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
      - gateway-server

  customers-service:
    image: benwilcock/spring-petclinic-customers-service:2.4.3
    container_name: customers-service
    mem_limit: 1024M
    ports:
      - 8081:8081
    environment:
      - PORT=8081
      - SPRING_PROFILES_ACTIVE=docker
      - CONFIG_SERVER_URI=http://config-server:8888
      - DISCOVERY_SERVER_URI=http://discovery-server:8761/eureka
    depends_on:
      - config-server
      - discovery-server
      - gateway-server
