# Other defaults needed by the CONFIG-SERVER
# Note that these don't come from GIT like the other Apps!
server:
  port: ${PORT}

spring:
  zipkin:
    enabled: true
    baseUrl: ${TRACING_SERVER_URI}

management:
  endpoints:
    web:
      exposure.include: '*'
